model:
  input_dim: 5
  hidden_dims: [64, 32, 16]
  dropout_rate: 0.3
  use_batch_norm: true
  activation: relu

training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 15
  
  # Optimizer settings
  optimizer: adam
  optimizer_params:
    betas: [0.9, 0.999]
    eps: 1e-08
  
  # Scheduler settings
  scheduler: reduce_on_plateau
  scheduler_params:
    mode: min
    patience: 5
    factor: 0.5
    min_lr: 1e-6

validation:
  # Overfitting check
  max_train_val_gap: 0.1  # Maximum acceptable gap between train and val accuracy
  
  # Convergence check
  convergence_window: 5  # Number of epochs to check for convergence
  convergence_threshold: 0.01  # Relative change threshold

data:
  train_path: data/processed/train.csv
  val_path: data/processed/val.csv
  test_path: data/processed/test.csv
  
  # Data augmentation (if needed)
  augmentation:
    noise_std: 0.01
    enabled: false

logging:
  level: INFO
  log_dir: logs/
  tensorboard: true

experiment:
  name: nicu_kangaroo_care_baseline
  seed: 42
  description: "Binary classification for NICU kangaroo care readiness"